# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_reconnect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reconnect',
            old_name='user_id',
            new_name='user',
        ),
    ]
